TEMPLATES = {
    'clients': 'clients/template',
    'groups': 'groups/template',
    'loanproducts': 'loanproducts/template',
    'loanproducts_mix': 'loanproducts/template?isProductMixTemplate=true',
    'loans': 'loans/template?clientId={}',
    'loan_transactions': 'loans/{}/transactions/template',
    'charges': 'charges/template',
    'offices': 'offices/template',
    'users': 'users/template',
    'hooks': 'hooks/template',
    'audits': 'audits/searchtemplate',
    'markercheckers': 'markercheckers/searchtemplate',
    'reports': 'reports/template',
    'accountingrules': 'accountingrules/template',
    'savingproducts': 'savingproducts/template',
    'savingsaccounts': 'savingsaccounts/template?clientId={}',
    'savingsaccounts_transactions': 'savingsaccounts/{}/transactions/template',
    'standinginstructions': 'standinginstructions/template',
    'accounttransfers': 'accounttransfers/template',
}